# Copyright (C) 2020-2024 CERN and UCLouvain.
# Licensed under the GNU Lesser General Public License (version 3 or later).
# Created by: A. Valassi (Sep 2024) for the MG5aMC CUDACPP plugin.
# Further modified by: A. Valassi (2024) for the MG5aMC CUDACPP plugin.

name: Archiver

on:
  push:
    tags: [ '*' ]

jobs:
  archiver:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: archive
      run: .github/workflows/archiver.sh
    - name: release
      # See https://github.com/softprops/action-gh-release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: [ cudacpp.tar.gz, VERSION ]
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
