# Copyright (C) 2020-2023 CERN and UCLouvain.
# Licensed under the GNU Lesser General Public License (version 3 or later).
# Created by: A. Valassi (Oct 2023) for the MG5aMC CUDACPP plugin.
# Further modified by: A. Valassi (2023) for the MG5aMC CUDACPP plugin.

name: Manual test suite

on:
  push:
    paths:
      - '.github/workflows/manual.*'
  workflow_dispatch:
    #inputs:
    #  name:
    #    description: 'Person to greet'
    #    default: 'World'
    #    required: true
    #    type: string

jobs:
  manualtestsuite:
    runs-on: ubuntu-latest
    steps:
    # See https://github.com/actions/checkout
    # (NB actions/checkout@v2 is deprecated)
    # (NB actions/checkout@v4 need "Allow owner and select non-owner" and "Allow actions created by github")
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: welcome
      run: .github/workflows/manual.sh welcome
    - name: codegen
      run: .github/workflows/manual.sh codegen
    - name: tput_ini
      run: .github/workflows/manual.sh tput_ini
    - name: tput_run
      run: .github/workflows/manual.sh tput_run
    - name: tput_fin
      run: .github/workflows/manual.sh tput_fin
    #- name: Send greeting
    #  run: echo "Hello ${{ inputs.name }}"
