# Copyright (C) 2020-2023 CERN and UCLouvain.
# Licensed under the GNU Lesser General Public License (version 3 or later).
# Created by: A. Valassi (Nov 2023) for the MG5aMC CUDACPP plugin.
# Further modified by: A. Valassi (2023) for the MG5aMC CUDACPP plugin.

#----------------------------------------------------------------------------------------------------------------------------------

name: Test all processes

#----------------------------------------------------------------------------------------------------------------------------------

on:

  # Trigger the all-processes workflow when new changes to the workflow are pushed
  push:
    paths:
      - '.github/workflows/testsuite*'

  # Manually trigger the all-processes workflow
  workflow_dispatch:

#----------------------------------------------------------------------------------------------------------------------------------

jobs:

  # See https://stackoverflow.com/a/75337311
  oneprocess:
    strategy:
      fail-fast: false # important to see all results even if one fails (fail-fast is true by default)
      matrix:
        # FIXME? Can the list of supported processes be specified only once in oneprocess.yml or allprocesses.yml?
        process: [ee_mumu, gg_tt, gg_ttg, gg_ttgg, gg_ttggg, gg_tt01g, gq_ttq, pp_tt012j]
        suffix: [mad, sa]
    uses: ./.github/workflows/testsuite_oneprocess.yml
    with:
      process: ${{ matrix.process }}.${{ matrix.suffix }}

#----------------------------------------------------------------------------------------------------------------------------------
